WebMVC4/WebMVC4/Models/Post.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebMVC4.Models
{
    public class Post
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "mục này không đượ bỏ trống")]
        [StringLength(500, ErrorMessage = "nhập ký tự trong khoảng 20-500", MinimumLength = 20)]
        public string title { get; set; }
        [Required(ErrorMessage = "mục này không được để trống")]
        [StringLength(int.MaxValue, ErrorMessage = "nhập không quá 50 ký tự", MinimumLength = 50)]
        public string body { get; set; }
        [DataType(DataType.DateTime)]
        public DateTime DayCreated { get; set; }
        [DataType(DataType.DateTime)]
        public DateTime DayUpdated { get; set; }
        public string AccountID { get; set; }

        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Tag> Tags { set; get; }
    }
}

WebMVC4/WebMVC4/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMVC4.Models;

namespace WebMVC4.Controllers
{
    public class CommentController : Controller
    {
        private BlogDbContext db = new BlogDbContext();

        //
        // GET: /Comment/

        public ActionResult Index()
        {
            var comments = db.Comments.Include(c => c.Post);
            return View(comments.ToList());
        }

        //
        // GET: /Comment/Details/5

        public ActionResult Details(int id = 0)
        {
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        //
        // GET: /Comment/Create

        public ActionResult Create()
        {
            ViewBag.PostID = new SelectList(db.Posts, "ID", "title");
            return View();
        }

        //
        // POST: /Comment/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Comment comment, int idpost)
        {
            if (ModelState.IsValid)
            {
                comment.PostID = idpost;
                comment.DayCreated = DateTime.Now;
                comment.DayUpDated = DateTime.Now;
                db.Comments.Add(comment);
                db.SaveChanges();
                return RedirectToAction("Details/"+idpost, "Post");
            }

            ViewBag.PostID = new SelectList(db.Posts, "ID", "title", comment.PostID);
            return View(comment);
        }

        //
        // GET: /Comment/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            ViewBag.PostID = new SelectList(db.Posts, "ID", "title", comment.PostID);
            return View(comment);
        }

        //
        // POST: /Comment/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Comment comment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(comment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PostID = new SelectList(db.Posts, "ID", "title", comment.PostID);
            return View(comment);
        }

        //
        // GET: /Comment/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        //
        // POST: /Comment/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Comment comment = db.Comments.Find(id);
            db.Comments.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

WebMVC4/WebMVC4/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMVC4.Models;

namespace WebMVC4.Controllers
{
    public class PostController : Controller
    {
        private BlogDbContext db = new BlogDbContext();

        //
        // GET: /Post/

        public ActionResult Index()
        {
            return View(db.Posts.ToList());
        }

        //
        // GET: /Post/Details/5

        public ActionResult Details(int id = 0)
        {
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            ViewData["idpost"] = id;
            return View(post);
        }

        //
        // GET: /Post/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Post/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Post post)
        {
            if (ModelState.IsValid)
            {
                post.DayCreated = DateTime.Now;
                post.DayUpdated = DateTime.Now;
                db.Posts.Add(post);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(post);
        }

        //
        // GET: /Post/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Post post = db.Posts.Find(id);
            ViewData["post"] = id;
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        //
        // POST: /Post/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Post post)
        {
            if (ModelState.IsValid)
            {
                db.Entry(post).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(post);
        }

        //
        // GET: /Post/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        //
        // POST: /Post/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Post post = db.Posts.Find(id);
            db.Posts.Remove(post);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

WebMVC4/WebMVC4/Views/Post/Create.cshtml
@model WebMVC4.Models.Post

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Post</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.title)
            @Html.ValidationMessageFor(model => model.title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.body)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.body)
            @Html.ValidationMessageFor(model => model.body)
        </div>

        
        <div class="editor-label">
            @Html.LabelFor(model => model.AccountID)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AccountID)
            @Html.ValidationMessageFor(model => model.AccountID)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebMVC4/WebMVC4/Views/Post/Delete.cshtml
@model WebMVC4.Models.Post

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Post</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.title)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.title)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.body)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.body)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DayCreated)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DayCreated)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DayUpdated)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DayUpdated)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.AccountID)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.AccountID)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

WebMVC4/WebMVC4/Views/Post/Details.cshtml
@model WebMVC4.Models.Post

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Post</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.title)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.title)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.body)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.body)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DayCreated)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DayCreated)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DayUpdated)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DayUpdated)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.AccountID)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.AccountID)
    </div>
</fieldset>


@Html.Partial("_addComment", new WebMVC4.Models.Comment(), ViewData);

<fieldset>
    <legend>Comment</legend>
        @foreach(var comment in Model.Comments.OrderByDescending(x => x.DayCreated).Take(5))
        {
            <div class="display-field">
                <h2>Cach day: </h2>: @Html.DisplayFor(x => comment.LastTime)
            </div>
            <div class="display-field">
                @Html.DisplayFor(x => comment.Body)
            </div>
        }
</fieldset>

    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
        @Html.ActionLink("Back to List", "Index")
    </p>

WebMVC4/WebMVC4/Views/Post/Edit.cshtml
@model WebMVC4.Models.Post

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Post</legend>

        @Html.HiddenFor(model => model.ID)

        <div class="editor-label">
            @Html.LabelFor(model => model.title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.title)
            @Html.ValidationMessageFor(model => model.title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.body)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.body)
            @Html.ValidationMessageFor(model => model.body)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DayCreated)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DayCreated)
            @Html.ValidationMessageFor(model => model.DayCreated)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DayUpdated)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DayUpdated)
            @Html.ValidationMessageFor(model => model.DayUpdated)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.AccountID)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AccountID)
            @Html.ValidationMessageFor(model => model.AccountID)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebMVC4/WebMVC4/Views/Post/Index.cshtml
@model IEnumerable<WebMVC4.Models.Post>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.body)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DayCreated)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DayUpdated)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AccountID)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.body)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DayCreated)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DayUpdated)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AccountID)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

WebMVC4/WebMVC4/Views/Post/_addComment.cshtml
@model WebMVC4.Models.Comment

@using (Html.BeginForm("Create", "Comment", new { idpost = ViewData["idpost"]}))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Add Comment</legend>

        
        <div class="editor-field">
            @Html.EditorFor(model => model.Body)
            @Html.ValidationMessageFor(model => model.Body)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}